plugins:
  - rubocop-md
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'coverage/**/*'
    - 'doc/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - '*.gemspec'
    - 'vendor/bundle/**/*'
    - 'examples/*'

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Lint/DuplicateBranch:
  IgnoreLiteralBranches: true
  IgnoreConstantBranches: true

Lint/SuppressedException:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'lib/htauth/argon2.rb'

Lint/ReturnInVoidContext:
  Exclude:
    - 'lib/htauth/passwd_entry.rb'

Lint/Void:
  Exclude:
    - 'lib/htauth/passwd_entry.rb'

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 25
  Exclude:
    - 'tasks/**/*'
    - 'lib/htauth/cli/*'
    - 'lib/htauth/md5.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/htauth/md5.rb'
    - 'lib/htauth/file.rb'
    - 'lib/htauth/cli/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/htauth/cli/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/htauth/cli/*'
    - 'tasks/**/*'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/htauth/cli/*'
    - 'tasks/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/htauth/cli/*'
    - 'lib/htauth/md5.rb'

Naming/PredicateMethod:
  Exclude:
    - 'lib/htauth/algorithm.rb'
Naming/PredicatePrefix:
  Exclude:
    - 'lib/htauth/digest_file.rb'
    - 'lib/htauth/passwd_file.rb'

# keeps want to combine examples
Style/CombinableLoops:
  Exclude:
    - README.md

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/OpenStructUse:
  Exclude:
    - 'lib/htauth/cli/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

ThreadSafety/ClassInstanceVariable:
  Enabled: false
ThreadSafety/NewThread:
  Enabled: false
ThreadSafety/DirChdir:
  Enabled: false

Security/IoMethods:
  Enabled: false
