#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require "htauth/cli/passwd"
rescue LoadError
  path = File.expand_path(File.join(File.dirname(__FILE__), "..", "lib"))
  raise if $LOAD_PATH.include?(path)

  $LOAD_PATH << path
  retry
end

HTAuth::CLI::Passwd.new.run(ARGV, ENV)
